# piups_exporter
# Copyright (c) 2021, Brendon Matheson
#
# http://brendonmatheson.com/
#
# This work is offered under the terms of the MIT license.  See the LICENSE file for details.

tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: admin
  password: admin

bearerAuth:
  enabled: false
  signingKey: my_secret_key

scripts:
  - name: piups
    script: ./scripts/piups.py

